name: build, test & publish on all platforms

on:
  push:
    tags:
      - '*'

jobs:
  verify-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all tags and history

      - name: Get the latest commit SHA
        id: get_sha
        run: echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Check if commit is on main
        id: check_main
        run: |
          # List all branches containing the commit
          branches=$(git branch --contains ${{ env.COMMIT_SHA }})

          # Check if main is in the list of branches
          if [[ "$branches" == *"main"* ]]; then
            echo "COMMIT_ON_MAIN=true" >> $GITHUB_ENV
          else
            echo "COMMIT_ON_MAIN=false" >> $GITHUB_ENV
          fi

      - name: Exit if not on main
        if: env.COMMIT_ON_MAIN == 'false'
        run: |
          echo "This tag's commit is not on the main branch. Exiting workflow."
          exit 1

      - name: Verify and proceed
        if: env.COMMIT_ON_MAIN == 'true'
        run: echo "Tag is on main. Proceeding with the workflow..."

  linux-x64:
    needs: [verify-and-run]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: install bun
        uses: oven-sh/setup-bun@v2
        with:
            bun-version: latest

      - name: install dependencies
        run: |
          cd /home/runner/work/gild-cli/gild-cli/main && bun install

      - name: run tests
        run: |
          cd /home/runner/work/gild-cli/gild-cli/main && bun test --coverage

      - name: build binary
        run: |
          cd /home/runner/work/gild-cli/gild-cli/main && bun run make

      - name: upload to github releases
        uses: actions/upload-artifact@v4
        with:
          name: gild-cli_${{ github.ref_name }}_linux-x64
          path: /home/runner/work/gild-cli/gild-cli/main/dist/gild

  windows-x64:
    needs: [verify-and-run]
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: |
          cd D:/a/gild-cli/gild-cli/main
          bun install

      - name: run tests
        run: |
          cd D:/a/gild-cli/gild-cli/main && bun test --coverage

      - name: build binary
        run: |
          cd D:/a/gild-cli/gild-cli/main
          bun run make

      - name: upload to github releases
        uses: actions/upload-artifact@v4
        with:
          name: gild-cli_${{ github.ref_name }}_windows-x64
          path: D:/a/gild-cli/gild-cli/main/dist/gild.exe

  darwin-x64:
    needs: [verify-and-run]
    runs-on: macOS-13
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: |
          cd /Users/runner/work/gild-cli/gild-cli/main
          bun install

      - name: run tests
        run: |
          cd /Users/runner/work/gild-cli/gild-cli/main
          bun test --coverage

      - name: build binary # not using "make" script to be sure target is correct
        run: |
          cd /Users/runner/work/gild-cli/gild-cli/main
          bun build ./index.ts --compile --target=bun-darwin-x64 --outfile dist/gild

      - name: upload to github releases
        uses: actions/upload-artifact@v4
        with:
          name: gild-cli_${{ github.ref_name }}_darwin-x64
          path: /Users/runner/work/gild-cli/gild-cli/main/dist/gild

  darwin-arm64:
    needs: [verify-and-run]
    runs-on: macOS-latest 
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: |
          cd /Users/runner/work/gild-cli/gild-cli/main
          bun install

      - name: run tests
        run: |
          cd /Users/runner/work/gild-cli/gild-cli/main
          bun test --coverage

      - name: build binary # not using "make" script to be sure target is correct
        run: |
          cd /Users/runner/work/gild-cli/gild-cli/main
          bun build ./index.ts --compile --target=bun-darwin-arm64 --outfile dist/gild

      - name: upload to github releases
        uses: actions/upload-artifact@v4
        with:
          name: gild-cli_${{ github.ref_name }}_darwin-arm64
          path: /Users/runner/work/gild-cli/gild-cli/main/dist/gild

  linux-x64-binary-test:
    needs: [linux-x64]
    runs-on: ubuntu-latest
    steps:
      - name: download all artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

  darwin-x64-binary-test:
    needs: [darwin-x64]
    runs-on: macOS-13 # should default to x64, TODO: might need to specify target some how
    steps:
      - name: download all artifacts
        uses: actions/download-artifact@v4

      - name: confirm which arch
        run: uname -m

      - name: Display structure of downloaded files
        run: ls -R

  darwin-arm64-binary-test:
    needs: [darwin-arm64]
    runs-on: macOS-latest # defaults to arm64 as of macOS14
    steps:
      - name: download all artifacts
        uses: actions/download-artifact@v4

      - name: confirm which arch
        run: uname -m

      - name: Display structure of downloaded files
        run: ls -R

  windows-x64-binary-test:
    needs: [windows-x64]
    runs-on: windows-latest # defaults to 2022, TODO: might be worth tested 2019 also
    steps:
      - name: download all artifacts
        uses: actions/download-artifact@v4

      - name: confirm which arch
        run: wmic cpu get DataWidth

      - name: Display structure of downloaded files
        run: Get-ChildItem -Recurse

  binary-tests:
    needs: [linux-x64-binary-test, darwin-x64-binary-test, darwin-arm64-binary-test, windows-x64-binary-test]
    runs-on: ubuntu-latest
    steps:
      - name: download all artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

  publish-linux-x64-to-npm:
    needs: [binary-tests]
    runs-on: ubuntu-latest      
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      CURRENT_TAG: ${{ github.ref_name }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: download all artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Install jq
        shell: bash
        run: |
          sudo apt-get install jq -y

      - name: Prepare linux-x64's package.json and copy binary artifact
        shell: bash
        run: |
          jq ". + {version: \"${{ env.CURRENT_TAG }}\"}" npm/gild-linux-x64/package.json > npm/gild-linux-x64/package.tmp.json && mv npm/gild-linux-x64/package.tmp.json npm/gild-linux-x64/package.json
          cp ./gild-cli_${{ env.CURRENT_TAG }}_linux-x64/gild npm/gild-linux-x64/gild

      - name: configure npm & publish
        run: |
          cd npm/gild-linux-x64
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-windows-x64-to-npm:
    needs: [binary-tests]
    runs-on: ubuntu-latest      
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      CURRENT_TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      # - name: Display structure of downloaded files
      #   run: dir /s

      - name: Install jq
        shell: bash
        run: |
          sudo apt-get install jq -y

      - name: Prepare gild-windows-x64's package.json and copy binary artifact
        shell: bash
        run: |
          jq ". + {version: \"${{ env.CURRENT_TAG }}\"}" npm/gild-windows-x64/package.json > npm/gild-windows-x64/package.tmp.json && mv npm/gild-windows-x64/package.tmp.json npm/gild-windows-x64/package.json
          cp gild-cli_${{ env.CURRENT_TAG }}_windows-x64/gild.exe npm/gild-windows-x64/gild.exe

      - name: Configure npm & publish
        run: |
          cd npm/gild-windows-x64
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-darwin-x64-to-npm:
    needs: [binary-tests]
    runs-on: ubuntu-latest      
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      CURRENT_TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Install jq
        shell: bash
        run: |
          sudo apt-get install jq -y

      - name: Prepare gild-darwin-x64's package.json and copy binary artifact
        shell: bash
        run: |
          jq ". + {version: \"${{ env.CURRENT_TAG }}\"}" npm/gild-darwin-x64/package.json > npm/gild-darwin-x64/package.tmp.json && mv npm/gild-darwin-x64/package.tmp.json npm/gild-darwin-x64/package.json
          cp ./gild-cli_${{ env.CURRENT_TAG }}_darwin-x64/gild npm/gild-darwin-x64/gild

      - name: Configure npm & publish
        run: |
          cd npm/gild-darwin-x64
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-darwin-arm64-to-npm:
    needs: [binary-tests]
    runs-on: ubuntu-latest      
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      CURRENT_TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Install jq
        shell: bash
        run: |
          sudo apt-get install jq -y

      - name: Prepare gild-darwin-arm64's package.json and copy binary artifact
        shell: bash
        run: |
          jq ". + {version: \"${{ env.CURRENT_TAG }}\"}" npm/gild-darwin-arm64/package.json > npm/gild-darwin-arm64/package.tmp.json && mv npm/gild-darwin-arm64/package.tmp.json npm/gild-darwin-arm64/package.json
          cp gild-cli_${{ env.CURRENT_TAG }}_darwin-arm64/gild npm/gild-darwin-arm64/gild

      - name: Configure npm & publish
        run: |
          cd npm/gild-darwin-arm64
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-main-to-npm:
    needs: [publish-windows-x64-to-npm, publish-linux-x64-to-npm, publish-darwin-x64-to-npm, publish-darwin-arm64-to-npm]
    runs-on: ubuntu-latest      
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      CURRENT_TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Install jq
        shell: bash
        run: |
          sudo apt-get install jq -y

      - name: Prepare package.json
        shell: bash
        run: |
          jq ". + {version: \"${{ env.CURRENT_TAG }}\"}" npm/gild/package.json > npm/gild/package.tmp.json && mv npm/gild/package.tmp.json npm/gild/package.json

      - name: Configure npm & publish
        run: |
          cd npm/gild
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}